name = "notify-cfbot"
type = "javascript"
route = ""
# Dev environment is deployed to a workers.dev domain
workers_dev = true
# Use CF_ACCOUNT_ID instead
#account_id = ""
# Use CF_ZONE_ID instead
#zone_id = ""

[vars]
# Env vars for all environments
TEAMS_APP_ID = "5f9f184e-e03c-4f19-b095-2119b8536f6c"

# Specific env vars for the dev environment
AUTH_JWKS = "https://login.microsoftonline.com/d6d49420-f39b-4df7-a1dc-d59a935871db/discovery/v2.0/keys"
AUTH_ISSUER = "https://login.microsoftonline.com/d6d49420-f39b-4df7-a1dc-d59a935871db/v2.0"

[build]
command = "NODE_ENV=development npm run build"
watch_dir = "src"
upload = { format = "service-worker" }

[env.production.build]
command = "npm run build"
watch_dir = "src"
upload = { format = "service-worker" }

[env.production.vars]
# Specific env vars for the production environment
AUTH_JWKS = "https://login.botframework.com/v1/.well-known/keys"
AUTH_ISSUER = "https://api.botframework.com"
