name = "notify-cfbot"
type = "javascript"
route = ""
# Dev environment is deployed to a workers.dev domain
workers_dev = true
# Use CF_ACCOUNT_ID instead
#account_id = ""
# Use CF_ZONE_ID instead
#zone_id = ""

# KV namespaces for dev environment
kv_namespaces = [
    { binding = "WEBHOOKS", id = "118d5a0fd993412495eb4b7ae2e54241", preview_id = "71c1fe726f4447c5a408152bd771cf6c" }
]

[vars]
TEAMS_APP_ID = "81e2ddb7-7c62-4d4a-9506-55e6a7b159c0"
TEAMS_TOKEN_ENDPOINT = "https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token"
BASE_URL = "https://notify-cfbot.italypaleale.workers.dev"
AUTH_JWKS_URI = "https://login.botframework.com/v1/.well-known/keys"
AUTH_ISSUER = "https://api.botframework.com"

[build]
command = "npm run build"
watch_dir = "src"
upload = { format = "service-worker" }

#
# Local (dev) environment
#
[env.local]
# Use the preview ID for all
kv_namespaces = [
    { binding = "WEBHOOKS", id = "71c1fe726f4447c5a408152bd771cf6c", preview_id = "71c1fe726f4447c5a408152bd771cf6c" }
]

[env.local.build]
command = "NODE_ENV=development npm run build"
watch_dir = "src"
upload = { format = "service-worker" }

[env.local.vars]
TEAMS_APP_ID = "81e2ddb7-7c62-4d4a-9506-55e6a7b159c0"
TEAMS_TOKEN_ENDPOINT = "https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token"
BASE_URL = "http://127.0.0.1:8787"
# This uses the Bot Emulator
AUTH_JWKS_URI = "https://login.microsoftonline.com/d6d49420-f39b-4df7-a1dc-d59a935871db/discovery/v2.0/keys"
AUTH_ISSUER = "https://login.microsoftonline.com/d6d49420-f39b-4df7-a1dc-d59a935871db/v2.0"

#
# Production environment
#
[env.production]
workers_dev = true
route = "notifier.italypaleale.me/*"
kv_namespaces = [
    { binding = "WEBHOOKS", id = "27efc34f0f0d463b8f7780dd2315d687" }
]

[env.production.build]
command = "npm run build"
watch_dir = "src"
upload = { format = "service-worker" }

[env.production.vars]
TEAMS_APP_ID = "5f9f184e-e03c-4f19-b095-2119b8536f6c"
TEAMS_TOKEN_ENDPOINT = "https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token"
BASE_URL = "http://notifier.italypaleale.me"
AUTH_JWKS_URI = "https://login.botframework.com/v1/.well-known/keys"
AUTH_ISSUER = "https://api.botframework.com"
