# CI: deploys to dev

# Required secrets:
# CF_ACCOUNT_ID: Account ID for Cloudflare Workers
# CF_API_TOKEN: API token for Cloudflare (for the Workers CLI)

name: 'CI'

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: 'ubuntu-20.04'
    steps:
      - name: 'Check out code'
        uses: 'actions/checkout@v2'

      - name: 'Install Node.js'
        uses: 'actions/setup-node@v1'
        with:
          node-version: '16.x'

      - name: 'Build app'
        run: |
          npm ci
          npm run build

      - name: 'Deploy to dev environment'
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
