# Deploys to production, triggered manually

# Required secrets:
# CF_ACCOUNT_ID: Account ID for Cloudflare Workers
# CF_API_TOKEN: API token for Cloudflare (for the Workers CLI)
# CF_ZONE_ID: Zone ID for the Cloudflare domain

name: 'Production'

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: 'ubuntu-20.04'
    steps:
      - name: 'Check out code'
        uses: 'actions/checkout@v2'

      - name: 'Install Node.js'
        uses: 'actions/setup-node@v1'
        with:
          node-version: '16.x'

      - name: 'Build app'
        run: |
          npm ci
          npm run build

      - name: 'Publish app as artifact'
        uses: 'actions/upload-artifact@v2'
        with:
          name: 'dist'
          path: 'dist'

      - name: 'Deploy to production environment'
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: 'production'
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
